Apple Silicon を搭載した MacBook で起こる Docker 関連エラーの対処法を追記
nnn-training/faq pull request #73
Opened 2024-02-20 10:05 UTC by dorimiamn

fix #72 

Apple Silicon 搭載 MacBook 向けのエラー対処法を追加しました。

- Prisma を使用する際に Docker コンテナがエラーを吐く問題の対処法を追加
- Docker コンテナを立ち上げる際に警告が出る場合の原因と対処法を追加

2024-02-24 03:56 UTC, Azumabashi requested changes
色々コメントと suggestion を書きましたが基本的には日本語の指摘になります。

2024-02-24 03:56 UTC, Azumabashi commented on MARKDOWN/intro/docker.md
> +以下のスクショで示された右上赤枠内の歯車アイコンをクリックしてください。
```suggestion
以下のスクリーンショットで示された右上赤枠内の歯車アイコンをクリックしてください。
```

2024-02-24 03:56 UTC, Azumabashi commented on MARKDOWN/intro/docker.md
> +そのチェックボックスをクリックして有効化してください。
スクリーンショットに当該の場所はあるので言い切ってしまった方が読みやすいです。
また `[` と `]` は余分そうです。

```suggestion
次に、Use Rosetta for x86/amd64 emulation on Apple Silicon と書かれたチェックボックスにチェックを入れ、Rosetta を有効化してください。
```

2024-02-24 03:56 UTC, Azumabashi commented on MARKDOWN/intro/docker.md
> +チェックボックスにチェックが入りましたら、右下の [Apply & Restart] をクリックして、 Docker Desktop を再起動してください。
```suggestion
チェックボックスにチェックを入れたら、右下の「Apply & Restart」と書かれたボタンをクリックして、 Docker Desktop を再起動してください。
```

2024-02-24 03:56 UTC, Azumabashi commented on MARKDOWN/intro/docker.md
> +これは、 Docker イメージのアーキテクチャの違いによって起きるエラーです。
「アーキテクチャ」の語を Docker イメージに対して適用するのは（意味は分かりますが）やや違和感があります。
おそらく [`--platform` のドキュメント](https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images) の `target platform` のことだと思うので、

```suggestion
これは、 Docker イメージが想定するアーキテクチャと実際のコンピュータのアーキテクチャの違いによって起きるエラーです。
```

とするのが自然な気がします。

2024-02-24 03:56 UTC, Azumabashi commented on MARKDOWN/intro/docker.md
> +教材では、 `Dockerfile` の 1 行目に `--platform=linux/x86_64` と書かれているかと思います。
```suggestion
教材では、 `Dockerfile` の 1 行目に `--platform=linux/x86_64` と書かれています。
```

2024-02-24 03:56 UTC, Azumabashi commented on MARKDOWN/intro/docker.md
> +つまり、 ARM アーキテクチャで動く CPU 上で AMD64 アーキテクチャを動かさなければなりません。
一般にはそうではない（ARM で動かしていれば ARM 向けイメージが動く）ので：

```suggestion
つまり、`--platform=linux/x86_64` を指定すると、ARM アーキテクチャで動く CPU 上で AMD64 アーキテクチャを動かさなければなりません。
```

cf. https://docs.docker.jp/engine/reference/builder.html#id39

2024-02-24 03:56 UTC, Azumabashi commented on MARKDOWN/intro/docker.md
> +このための仕組みとしてエミュレータが用意されており、変換して動いてくれるようになっています。
何を変換してくれているのかを書いた方がいいかもしれません。とはいえ機械語の話をしてもここでは過剰なので：

```suggestion
このための仕組みとしてエミュレータが用意されており、Docker イメージの対応するアーキテクチャと実際のコンピュータのアーキテクチャの差異を吸収してくれるようになっています。
```

2024-02-24 03:56 UTC, Azumabashi commented on MARKDOWN/intro/docker.md
> +教材では、 `Dockerfile` の 1 行目に `--platform=linux/x86_64` と書かれた記述を削除し、 `docker compose up -d --build` コマンドを実行すれば解決するはずです。
```suggestion
教材で提示された `Dockerfile` の 1 行目にある `--platform=linux/x86_64` を削除し、 `docker compose up -d --build` コマンドを実行すれば解決するはずです。
```

2024-02-24 03:56 UTC, Azumabashi commented on MARKDOWN/intro/docker.md
> +使っているパソコンのアーキテクチャと呼ばれるものが教材で指定したアーキテクチャと異なるため、パフォーマンスが低下する可能性があり、それを警告として表示しているものです。
```suggestion
使っているパソコンのアーキテクチャが Docker イメージが想定するものと異なるため、パフォーマンスが低下する可能性があり、それを警告として表示しているものです。
```

2024-02-27 05:31 UTC, dorimiamn commented on MARKDOWN/intro/docker.md
> +そのチェックボックスをクリックして有効化してください。
確かにスクリーンショット内で示されているならば、言い切ってしまって問題ありませんね。
ご指摘ありがとうございます！

2024-02-27 05:32 UTC, dorimiamn commented on MARKDOWN/intro/docker.md
> +チェックボックスにチェックが入りましたら、右下の [Apply & Restart] をクリックして、 Docker Desktop を再起動してください。
ボタンと明示するべきでした。
ご指摘ありがとうございます！

2024-02-27 05:43 UTC, dorimiamn commented on MARKDOWN/intro/docker.md
> +つまり、 ARM アーキテクチャで動く CPU 上で AMD64 アーキテクチャを動かさなければなりません。
前提となる条件が抜けていました。
特定の OS/ARCH を指定した時のみ、異なるアーキテクチャで動かさねばならないことを含めるべきでした。
ご指摘ありがとうございます！

2024-02-27 05:48 UTC, dorimiamn commented on MARKDOWN/intro/docker.md
> +このための仕組みとしてエミュレータが用意されており、変換して動いてくれるようになっています。
変換だけでは曖昧で疑問を持たせてしまいますね……。
提示していただいた記述であればエミュレータの存在意義が明確に感じられます！
ご指摘ありがとうございます！

2024-02-27 05:49 UTC, dorimiamn commented on MARKDOWN/intro/docker.md
> +使っているパソコンのアーキテクチャと呼ばれるものが教材で指定したアーキテクチャと異なるため、パフォーマンスが低下する可能性があり、それを警告として表示しているものです。
Docker イメージが想定するものとした方が冗長さが排除できて良いですね。
ありがとうございます！

2024-02-27 05:54 UTC, dorimiamn commented on MARKDOWN/intro/docker.md
> +これは、 Docker イメージのアーキテクチャの違いによって起きるエラーです。
意図しているのは `target platform` ですので、ご指摘の通りです。

>これは、 Docker イメージのアーキテクチャの違いによって起きるエラーです。

では、解釈に幅があってよろしくない表現ですね。

提示していただいた記述であれば platform を指定したニュアンスが含まれていて明瞭に感じます。

2024-02-27 05:55 UTC, dorimiamn commented
レビューしていただきありがとうございました！！

私の方で上手く言語化できていない部分を汲み取って表現を修正していただきとても助かります 🙇

2024-03-13 09:12 UTC, merged